### ISSUE TITLE
marathon running on https://

### ISSUE THREAD

**Issue by mrsln** [Tapad/sbt-marathon#2]
Hi! Thanks for the plugin!

Does it work with marathon running on https protocol?

I'm getting `400 The plain HTTP request was sent to HTTPS port` from Nginx. I've already tried to specify 443 port in the `marathonServiceUrl`.

Thanks!

**Comment by jeffreyolchovy** [comment]
@mrsln, `v1.2.0rc0` has been published with HTTPS support. Let me know if that works for you, and if so, I will promote it as the official v1.2.0 release.

**Comment by mrsln** [comment]
You're fast! Looks like it works now but I've got a problem passing basic auth creds. Do you know if it can be solved using the plugin? I've tried to use `marathonServiceUrl` (`https://user:password@host", but it gave me this exception
```
	at scala.sys.package$.error(package.scala:27)
	at sbtmarathon.MarathonSettings$$anonfun$defaultSettings$3.apply(MarathonSettings.scala:50)
	at sbtmarathon.MarathonSettings$$anonfun$defaultSettings$3.apply(MarathonSettings.scala:45)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
```

then I've tried to decode it but it gave me even cooler exception:
```

**Comment by jeffreyolchovy** [comment]
Hmm, basic auth should work by passing the creds via URL as it looks like you're doing.

I've [added test cases to the MarathonServiceFunctionalSpec](https://github.com/Tapad/sbt-marathon/pull/3/commits/5a06ac71a36e0d5d9c4b702caee65ef5d0f855e6) that shows the underlying service abstraction should work with basic auth credentials, and a [scripted end-to-end test](https://github.com/Tapad/sbt-marathon/pull/3/commits/c17aebf26f32aa79bdf3e3738879f814d9b67fa0) that shows your sbt project should not halt on startup if you supply a URL with basic auth credentials as your `marathonServiceUrl`.

Please review both of those changesets and try to use them as examples and let me know if it still doesn't work for you and I can investigate further.

**Comment by mrsln** [comment]
should've mentioned that I have slash ("/") and a question mark in the password ("?"). Something like - `PAsw/or?d=`

**Comment by jeffreyolchovy** [comment]
Ah, ok, percent encoding is most likely what you want to do then: https://stackoverflow.com/questions/6718471/escaping-username-characters-in-basic-auth-urls.

**Comment by mrsln** [comment]
I've tried to encode the password but it didn't work. I've tried to use a password without any special characters - no luck. The tests you've metioned are using 'example.com' that doesn't require authorization so maybe they're not correct. I'm getting "401 Authorization Required" from nginx but everything OK if I'm using a browser.

**Comment by jeffreyolchovy** [comment]
I've made two changes:
1. Use TLS without validation, in case there is an issue with certificates
2. Use httpbin.org instead of example.com to truly test that the Basic Auth routine does work

As of the last changeset to the bugfix/support-https branch, it is proven that Basic Auth does indeed work using these abstractions. I've published `v0.1.2rc1` (you may need to wait a few minutes until artifacts sync to Maven Central) -- please try that and see if it makes any difference. If it still doesn't work, maybe you can provide me with a private gist of your project setup and any additional context to try to tackle the underlying cause of your problem.

**Comment by mrsln** [comment]
In the basic-auth test try to make a POST request instead of GET. I've left a comment on the specific line of the code.

**Comment by jeffreyolchovy** [comment]
Sorry, but unfortunately that error is not due to this abstraction. A POST request is not allowed on the httpbin.org server at that endpoint so it will return a 405 regardless.

You can verify that behavior with curl:
```
$ curl -XPOST 'https://user:password@httpbin.org/basic-auth/user/password'
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>
```

**Comment by jeffreyolchovy** [comment]
Ok @mrsln, since I don't have (1) an instance of Marathon behind basic auth and (2) a general HTTP endpoint that accepts POST requests that uses basic auth (i.e. example.com and httpbin.org only are able to take me so far), I created a mock Marathon server that employs a basic auth scheme.

There are now functional tests that use this mock, and it appears that Finagle is not attaching the proper Authorization header for the non-GET methods (as I believe you were hinting at). 

I put back a routine that I originally had which will append the correct Authorization header value if user credentials are present on the URL.

I just released `v0.1.2rc2` which contains this logic. Please give that another try and let me know how it goes.

**Comment by mrsln** [comment]
It works! You're a legend!

**Comment by jeffreyolchovy** [comment]
Excellent! I'll rebase, clean up the commit history, and publish the official release version soon.

**Comment by mrsln** [comment]
Don't forget to update MarathonService.instanceServiceUrl - https://github.com/Tapad/sbt-marathon/blob/master/marathon/src/main/scala/sbtmarathon/MarathonService.scala#L90

Update, Destroy, Scale don't work because of this.

**Comment by jeffreyolchovy** [comment]
Good catch. I will also make sure the mock authenticating server tests execute these types of requests to prevent regressions. Thanks!
